import nodemailer from "nodemailer";

/**
 * Input structure for dispatching a single email with QR attachment.
 * Contains attendee name, email, control number, and path to QR image file.
 */
export interface EmailDispatchEntry {
  name: string;
  email: string;
  controlNumber: string;
  qrFilePath: string;
}

/**
 * Result of dispatching a batch of emails.
 * Tracks how many succeeded, failed, and whether SMTP is configured.
 */
export interface EmailDispatchResult {
  enabled: boolean; // Whether SMTP is configured and available
  sentCount: number; // Number of emails successfully sent
  failed: Array<{ email: string; reason: string }>; // Failed deliveries with reasons
}

/**
 * Reads SMTP configuration from environment variables.
 * Returns null if required environment variables are missing.
 * Required: SMTP_HOST, SMTP_USER, SMTP_PASS, SMTP_FROM
 * Optional: SMTP_PORT (defaults to 587), SMTP_SECURE (defaults to false)
 */
function getSmtpConfig() {
  const host = process.env.SMTP_HOST!.trim(); // env must be available
  const port = Number(process.env.SMTP_PORT ?? "587");
  const user = process.env.SMTP_USER!.trim();
  const pass = process.env.SMTP_PASS!.trim();
  const from = process.env.SMTP_FROM!.trim();
  const secure = (process.env.SMTP_SECURE ?? "false").toLowerCase() === "true";

  // Return null if any required config is missing
  if (!host || !user || !pass || !from) {
    return null;
  }

  return {
    host,
    port,
    user,
    pass,
    from,
    secure,
  };
}

/**
 * Sends emails sequentially (one at a time) with QR code attachments.
 * Processes each email individually to avoid rate-limiting and ensure reliability.
 * Catches errors per email so one failure doesn't stop the rest.
 * Returns summary of sent and failed emails.
 *
 * Why sequential?
 * - Prevents SMTP rate-limit issues
 * - Easier to debug individual failures
 * - Predictable behavior in real-world event environments
 */
export async function sendSequentialEmails(
  entries: EmailDispatchEntry[],
  logFn: (eventName: string, details?: Record<string, unknown>) => void,
): Promise<EmailDispatchResult> {
  // Get SMTP configuration from environment variables
  const smtp = getSmtpConfig();

  // If SMTP is not configured, return disabled status
  if (!smtp) {
    return {
      enabled: false,
      sentCount: 0,
      failed: [],
    };
  }

  // Create email transporter with SMTP credentials
  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.secure,
    auth: {
      user: smtp.user,
      pass: smtp.pass,
    },
  });

  let sentCount = 0;
  const failed: Array<{ email: string; reason: string }> = [];

  // Send emails one at a time (sequential, not parallel)
  for (const entry of entries) {
    try {
      // Send email with QR code attachment
      await transporter.sendMail({
        from: smtp.from,
        to: entry.email,
        subject: "Your Kichi QR Code",
        text: `Hello ${entry.name},\n\nAttached is your QR code for event access.\nControl number: ${entry.controlNumber}\n\nGenerated by Kichi.`,
        attachments: [
          {
            filename: `${entry.controlNumber}.png`,
            path: entry.qrFilePath,
            contentType: "image/png",
          },
        ],
      });

      // Increment success counter and log event
      sentCount += 1;
      logFn("Email sent", {
        email: entry.email,
        controlNumber: entry.controlNumber,
      });
    } catch (error) {
      // Catch error for this email and continue with next
      const reason =
        error instanceof Error ? error.message : "Unknown SMTP error";
      failed.push({ email: entry.email, reason });
      logFn("Email failed", {
        email: entry.email,
        controlNumber: entry.controlNumber,
        reason,
      });
    }
  }

  // Return summary of results
  return {
    enabled: true,
    sentCount,
    failed,
  };
}
