import nodemailer from "nodemailer";
import { ITINERARY_IMAGE_PATH } from "../lib/constants";

/**
 * Input structure for dispatching a single email with QR attachment.
 * Contains attendee name, email, control number, and QR file metadata.
 */
export interface EmailDispatchEntry {
  name: string;
  email: string;
  controlNumber: string;
  qrFileName: string;
  qrFilePath: string;
}

/**
 * Result of dispatching a batch of emails.
 * Tracks how many succeeded, failed, and whether SMTP is configured.
 */
export interface EmailDispatchResult {
  enabled: boolean; // Whether SMTP is configured and available
  sentCount: number; // Number of emails successfully sent
  sent: Array<{ name: string; email: string; controlNumber: string }>; // Sent deliveries
  failed: Array<{
    name: string;
    email: string;
    controlNumber: string;
    reason: string;
  }>; // Failed deliveries with reasons
}

/**
 * Reads SMTP configuration from environment variables.
 * Returns null if required environment variables are missing.
 * Required: SMTP_HOST, SMTP_USER, SMTP_PASS, SMTP_FROM
 * Optional: SMTP_PORT (defaults to 587), SMTP_SECURE (defaults to false)
 */
function getSmtpConfig() {
  const host = process.env.SMTP_HOST!.trim(); // env must be available
  const port = Number(process.env.SMTP_PORT ?? "587");
  const user = process.env.SMTP_USER!.trim();
  const pass = process.env.SMTP_PASS!.trim();
  const from = process.env.SMTP_FROM!.trim();
  const secure = (process.env.SMTP_SECURE ?? "false").toLowerCase() === "true";

  // Return null if any required config is missing
  if (!host || !user || !pass || !from) {
    return null;
  }

  return {
    host,
    port,
    user,
    pass,
    from,
    secure,
  };
}

/**
 * Sends emails sequentially (one at a time) with QR code attachments.
 * Processes each email individually to avoid rate-limiting and ensure reliability.
 * Catches errors per email so one failure doesn't stop the rest.
 * Returns summary of sent and failed emails.
 *
 * Why sequential?
 * - Prevents SMTP rate-limit issues
 * - Easier to debug individual failures
 * - Predictable behavior in real-world event environments
 */
export async function sendSequentialEmails(
  entries: EmailDispatchEntry[],
  logFn: (eventName: string, details?: Record<string, unknown>) => void,
): Promise<EmailDispatchResult> {
  // Get SMTP configuration from environment variables
  const smtp = getSmtpConfig();

  // If SMTP is not configured, return disabled status
  if (!smtp) {
    return {
      enabled: false,
      sentCount: 0,
      sent: [],
      failed: [],
    };
  }

  // Create email transporter with SMTP credentials
  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.secure,
    auth: {
      user: smtp.user,
      pass: smtp.pass,
    },
  });

  let sentCount = 0;
  const sent: Array<{ name: string; email: string; controlNumber: string }> =
    [];
  const failed: Array<{
    name: string;
    email: string;
    controlNumber: string;
    reason: string;
  }> = [];

  // Send emails one at a time (sequential, not parallel)
  for (const entry of entries) {
    try {
      const generatedOn = new Date().toISOString().slice(0, 10);
      const controlLine = `Control number: ${entry.controlNumber}`;
      const controlLineEs = `Numero de control: ${entry.controlNumber}`;

      const englishMessage = [
        `Good day ${entry.name},`,
        "",
        "We hope you are doing very well. We are pleased to inform you that your registration has been successfully completed.",
        "",
        "Attached to this email you will find your QR access code and itinerary, which you must present on the day of the event for entry and validation.",
        controlLine,
        "",
        "We recommend keeping this email and having your QR code available in digital or printed format.",
        "",
        "We appreciate your participation and remain at your service for any questions or additional information.",
        "",
        "Best regards.",
        "",
        `Generated by Kichi on ${generatedOn}.`,
      ].join("\n");

      const spanishMessage = [
        `Buen día ${entry.name},`,
        "",
        "Esperando se encuentre muy bien, le informamos que su registro ha sido realizado exitosamente.",
        "",
        "Adjunto a este correo encontrará su código QR de acceso e itinerario, el cual deberá presentar el día del evento para su ingreso y validación.",
        controlLineEs,
        "",
        "Le recomendamos conservar este correo y tener disponible su código QR en formato digital o impreso.",
        "",
        "Agradecemos su participación y quedamos a sus órdenes para cualquier duda o información adicional.",
        "",
        "Saludos cordiales.",
        "",
        `Generado por Kichi el ${generatedOn}.`,
      ].join("\n");

      const text = `${englishMessage}\n\n---\n\n${spanishMessage}`;

      // Send email with QR code attachment
      await transporter.sendMail({
        from: smtp.from,
        to: entry.email,
        subject: "Your Kichi QR Code",
        text,
        attachments: [
          {
            filename: entry.qrFileName,
            path: entry.qrFilePath,
            contentType: "image/png",
          },
          {
            filename: "Itinerario.png",
            path: ITINERARY_IMAGE_PATH,
            contentType: "image/png",
          },
        ],
      });

      // Increment success counter and log event
      sentCount += 1;
      sent.push({
        name: entry.name,
        email: entry.email,
        controlNumber: entry.controlNumber,
      });
      logFn("Email sent", {
        email: entry.email,
        controlNumber: entry.controlNumber,
      });
    } catch (error) {
      // Catch error for this email and continue with next
      const reason =
        error instanceof Error ? error.message : "Unknown SMTP error";
      failed.push({
        name: entry.name,
        email: entry.email,
        controlNumber: entry.controlNumber,
        reason,
      });
      logFn("Email failed", {
        email: entry.email,
        controlNumber: entry.controlNumber,
        reason,
      });
    }
  }

  // Return summary of results
  return {
    enabled: true,
    sentCount,
    sent,
    failed,
  };
}
