export type Language = "es" | "en";

export const copy = {
  es: {
    nav: {
      toolkit: "Toolkit",
      language: "ES",
    },
    landing: {
      heroTitle: "Ingresa una tabla de Excel, genera un lote QR",
      heroSubtitle:
        "Crea, personaliza y administra codigos QR desde tus hojas de datos.",
      cta: "Comenzar",
      trusted: "Con la confianza de profesionales en",
    },
    sidebar: {
      title: "Kichi Toolkit",
      subtitle: "Sincronizacion local",
      home: "Home",
      batch: "Generador de lotes",
      email: "Entrega de correos",
      scanner: "Escaner",
      status: "Estado: Local",
    },
    generator: {
      title: "Generar lote QR",
      subtitle:
        "Suelta tu CSV o XLSX, revisa las columnas y crea el lote en segundos.",
      dropTitle: "arrastra y suelta tu hoja",
      dropSubtitle: "o haz clic en explorar y selecciona un archivo",
      noFile: "Ningun archivo seleccionado.",
      browse: "Explorar archivo",
      demo: "Usar archivo demo CSV",
      analyze: "Analizar columnas",
      waiting: "Esperando archivo.",
      demoLoadFailed: "No se pudo cargar el CSV demo.",
      mappingTitle: "Mapear columnas",
      mappingSubtitle:
        "Selecciona las columnas para Nombre y Correo (obligatorios).",
      labelName: "Nombre",
      labelEmail: "Correo",
      sendEmailsAction: "Enviar por correo",
      generate: "Generar lote QR",
      resultsTitle: "Resultados",
      rows: "filas",
      generated: "generados",
      failed: "fallidos",
      emailsSent: "correos enviados",
      zip: "Descargar lote ZIP",
      qrList: "qr generados",
      failures: "fallos",
      downloadQr: "Descargar QR",
      noFailures: "Sin fallos.",
      selectedFile: "Seleccionado: {name} ({size} KB)",
      fileSelected: "Archivo seleccionado. Haz clic en Analizar columnas.",
      fileDropped: "Archivo soltado. Haz clic en Analizar columnas.",
      selectFileFirst: "Selecciona o suelta primero un archivo CSV/XLSX.",
      loadingDemo: "Cargando CSV demo...",
      demoLoaded: "CSV demo cargado. Haz clic en Analizar columnas.",
      demoMissing: "No se encontro el CSV demo en assets publicos.",
      analyzing: "Analizando columnas...",
      parseFailed: "No se pudo analizar el archivo.",
      columnsReady: "Columnas listas. Filas detectadas: {rows}.",
      mappingMissing: "Faltan columnas obligatorias (nombre y correo).",
      generating: "Generando lote QR...",
      sendingEmails: "Enviando correos...",
      sendEmailsFailed: "No se pudieron enviar los correos.",
      noEmailTargets: "No hay correos disponibles para enviar.",
      generationFailed: "La generacion fallo.",
      batchCompleted: "Lote completado.",
      rowPrefix: "Fila",
      generalPrefix: "General",
    },
    footer: {
      left: "// kichi - qr toolkit para eventos",
      right: "hecho para organizadores que quieren herramientas precisas",
    },
    partners: "Con la confianza de profesionales en",
    scanner: {
      title: "Escaner de Asistentes",
      status: "PROCESAMIENTO LOCAL ACTIVO",
      readyTitle: "Listo para escanear",
      readySubtitle:
        "Esperando entrada del escaner de hardware o camara. El procesamiento se realiza localmente sin necesidad de conexion a internet.",
      latestStatus: "Escaneo exitoso",
      latestTitle: "Informacion del Asistente",
      uuidLabel: "UUID",
      activityTitle: "Actividad Reciente",
      activityAction: "Ver Registro Completo",
      activityActionLess: "Ver solo 7",
      activityUnknown: "-- DESCONOCIDO --",
      activityInvalid: "Codigo invalido",
      fieldName: "Nombre Completo",
      fieldRole: "Rol",
      fieldCompany: "Email/Correo",
      fieldControl: "Numero de Control",
    },
    email: {
      title: "Entrega de correos",
      batchLabel: "BATCH_ID",
      statusLabel: "Estado",
      statusValue: "ENVIANDO",
      progressCompleted: "{sent} / {total} completados",
      progressRemaining: "Est. restante: {eta}",
      logTitle: "Registro de envios",
      logToggleMore: "Ver todo",
      logToggleLess: "Ver solo 7",
      logSentLabel: "Entregado",
      logFailedLabel: "Error",
      summaryTitle: "Resumen del lote",
      summaryTotal: "Total asistentes",
      summarySent: "Correos enviados",
      summaryPending: "Pendientes",
      summaryFailed: "Fallos",
      controlsTitle: "Controles",
      actionCancel: "Cancelar envio",
      actionRetry: "Reintentar fallidos",
      configTitle: "SMTP",
      configUser: "SMTP User",
      configFrom: "SMTP_FROM",
      notConfigured: "no configurado",
    },
  },
  en: {
    nav: {
      toolkit: "Toolkit",
      language: "EN",
    },
    landing: {
      heroTitle: "Spreadsheet in,\nQR batch out.",
      heroSubtitle:
        "Effortlessly create, customize, and manage QR codes from your data sheets.",
      cta: "Start",
      trusted: "Trusted by professionals at",
    },
    sidebar: {
      title: "Kichi Toolkit",
      subtitle: "Local-first syncing",
      home: "Home",
      batch: "Batch Generator",
      email: "Email Delivery",
      scanner: "Scanner",
      status: "Status: Local",
    },
    generator: {
      title: "Generate QR batch",
      subtitle:
        "Drop your CSV or XLSX, review the columns, and create the batch in seconds.",
      dropTitle: "drag and drop spreadsheet",
      dropSubtitle: "or click browse and select a file",
      noFile: "No file selected.",
      browse: "Browse file",
      demo: "Use demo CSV file",
      analyze: "Analyze columns",
      waiting: "Waiting for file.",
      demoLoadFailed: "Failed to load the demo CSV.",
      mappingTitle: "Map columns",
      mappingSubtitle: "Map Name and Email (required) columns.",
      labelName: "Name",
      labelEmail: "Email",
      sendEmailsAction: "Send via email",
      generate: "Generate QR batch",
      resultsTitle: "Results",
      rows: "rows",
      generated: "generated",
      failed: "failed",
      emailsSent: "emails sent",
      zip: "Download ZIP batch",
      qrList: "generated qr files",
      failures: "failures",
      downloadQr: "Download QR",
      noFailures: "No failures.",
      selectedFile: "Selected: {name} ({size} KB)",
      fileSelected: "File selected. Click Analyze columns.",
      fileDropped: "File dropped. Click Analyze columns.",
      selectFileFirst: "Select or drop a CSV/XLSX file first.",
      loadingDemo: "Loading demo CSV...",
      demoLoaded: "Demo CSV loaded. Click Analyze columns.",
      demoMissing: "Demo CSV not found in public assets.",
      analyzing: "Analyzing columns...",
      parseFailed: "Failed to parse file.",
      columnsReady: "Columns ready. Rows detected: {rows}.",
      mappingMissing: "Required columns (name and email) are missing.",
      generating: "Generating QR batch...",
      sendingEmails: "Sending emails...",
      sendEmailsFailed: "Failed to send emails.",
      noEmailTargets: "No email recipients available.",
      generationFailed: "Generation failed.",
      batchCompleted: "Batch completed.",
      rowPrefix: "Row",
      generalPrefix: "General",
    },
    footer: {
      left: "// kichi - qr toolkit for events",
      right: "built for organizers who like sharp tools",
    },
    partners: "Trusted by professionals at",
    scanner: {
      title: "Attendee Scanner",
      status: "LOCAL PROCESSING ACTIVE",
      readyTitle: "Ready to scan",
      readySubtitle:
        "Waiting for hardware scanner or camera input. Processing happens locally without needing the internet.",
      latestStatus: "Scan successful",
      latestTitle: "Attendee details",
      uuidLabel: "UUID",
      activityTitle: "Recent Activity",
      activityAction: "View Full Log",
      activityActionLess: "Show latest 7",
      activityUnknown: "-- UNKNOWN --",
      activityInvalid: "Invalid code",
      fieldName: "Full Name",
      fieldRole: "Role",
      fieldCompany: "Email/Correo",
      fieldControl: "Control Number",
    },
    email: {
      title: "Email delivery",
      batchLabel: "BATCH_ID",
      statusLabel: "Status",
      statusValue: "SENDING",
      progressCompleted: "{sent} / {total} completed",
      progressRemaining: "ETA: {eta}",
      logTitle: "Delivery log",
      logToggleMore: "See all",
      logToggleLess: "Show latest 7",
      logSentLabel: "Delivered",
      logFailedLabel: "Failed",
      summaryTitle: "Batch summary",
      summaryTotal: "Total attendees",
      summarySent: "Emails sent",
      summaryPending: "Pending",
      summaryFailed: "Failures",
      controlsTitle: "Controls",
      actionCancel: "Cancel delivery",
      actionRetry: "Retry failed",
      configTitle: "SMTP",
      configUser: "SMTP User",
      configFrom: "SMTP_FROM",
      notConfigured: "not configured",
    },
  },
} as const;

export function formatText(
  template: string,
  params: Record<string, string | number> = {},
): string {
  return Object.entries(params).reduce(
    (output, [key, value]) => output.replace(`{${key}}`, String(value)),
    template,
  );
}
